EnergySite/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

from django.contrib import admin
from rest_framework import routers
from measurements import views as measurement_views
from flickr_images import views as flickr_images_views

admin.autodiscover()

api_router = routers.SimpleRouter()
api_router.register(r'^measurements', measurement_views.MeasurementViewSet)
api_router.register(r'^flickr-images', flickr_images_views.ImagesViewSet)

urlpatterns = patterns('',
    url(r'^$', TemplateView.as_view(template_name="index.html")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^devices/', include('devices.urls')),
    url(r'^facilities/', include('facilities.urls')),
    url(r'^measurements/', include('measurements.urls')),

    url(r'^api/', include(api_router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^accounts/profile/', 'facilities.views.process_oauth2_login'),
)

devices/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'EnergySite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', 'devices.views.index', name='index'),
    url(r'^add/', 'devices.views.add', name='add'),
    url(r'^view/', 'devices.views.view', name='view'),
    url(r'^remove/', 'devices.views.remove_device', name='remove')
)

devices/models.py
from django.db import models
from facilities.models import Facility


class Category(models.Model):
    category = models.CharField(max_length=80)


class Device(models.Model):
    facilities = models.ManyToManyField(Facility, related_name='devices')
    category = models.ForeignKey(Category)
    brand = models.CharField(max_length=80)
    model = models.CharField(max_length=80)

    def __unicode__(self):
        return u'{0}'.format(self.model)

facilities/models.py
from django.db import models
from django.contrib.auth.models import User


class Facility(models.Model):
    users = models.ManyToManyField(User, related_name='facilities')
    street = models.CharField(max_length=80)
    street2 = models.CharField(max_length=80)
    city = models.CharField(max_length=80)
    zipcode = models.CharField(max_length=80)
    inhabitants = models.IntegerField()
    email = models.CharField(max_length=80)
    phone_number = models.CharField(max_length=80)
    password = models.CharField(max_length=256)

    class Meta:
        permissions = (
            ("add_resident", "Can add a resident"),
            ("view_residents", "Can view residents"),
            ("edit_resident", "Can edit a resident"),
        )

templates/index.html
{% extends 'master.html' %}

{% block content %}
Test!
{% endblock %}

templates/master.html
<!doctype html>
<html>
<head>
    <title>Energy</title>

    {% load staticfiles %}

    <link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}"/>
    {% block styles %}{% endblock %}

    <script type="text/javascript" src="{% static "js/mootools/mootools-core-1.4.5.min.js" %}"></script>
    <script type="text/javascript" src="{% static "flickr_images/js/min/flickr-image-slider.min.js" %}"></script>
    {% block scripts %}{% endblock %}
</head>
<body>

<div class="grey-bar"></div>

<div class="wrapper">
    <div class="header">
        <nav>
            <ul>
                <li>
                    <a href="/">Home</a>
                </li>
                {% if not user.is_authenticated %}
                    <li><a href="{% url 'facilities.views.login' %}">Login</a></li>
                    <li><a href="{% url 'facilities.views.register' %}">Register</a></li>
                {% else %}
                    <li>
                        <a href="{% url 'facilities.views.index' %}">Facilities</a>
                        <ul>
                            {% if perms.facilities.add_facility %}
                                <li><a href="{% url 'facilities.views.add' %}">Add facility</a></li>
                            {% endif %}
                            <li><a href="{% url 'facilities.views.view' %}">View your facilities</a></li>
                            {% if perms.facilities.add_resident %}
                                <li><a href="{% url 'facilities.views.register_resident' %}">Register a resident</a></li>
                                <li><a href="{% url 'facilities.views.delete_resident' %}">Delete residents</a></li>
                            {% endif %}
                        </ul>
                    </li>
                    <li>
                        <a href="{% url 'measurements.views.index' %}">Measurements</a>
                        <ul>
                            <li><a href="{% url 'measurements.views.add' %}">Add measurement</a></li>
                        </ul>
                    </li>
                    {% if perms.devices.add_device %}
                        <li>
                            <a href="{% url 'devices.views.index' %}">Devices</a>
                            <ul>
                                <li><a href="{% url 'devices.views.add' %}">Add devices</a></li>
                                <li><a href="{% url 'devices.views.view' %}">View devices</a></li>
                                <li><a href="{% url 'devices.views.remove_device' %}">Remove devices</a></li>
                            </ul>
                        </li>
                    {% endif %}
                    <li><a href="{% url 'facilities.views.logout' %}">Logout</a></li>
                {% endif %}
                <li><a href="{% url 'measurements.views.view' %}">View measurement averages</a></li>
                <li><a href="{% url 'measurements.views.compare' %}">Compare measurements</a></li>
            </ul>
        </nav>
        <div class="clear"></div>
    </div>

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <div class="content">
        {% block content %}{% endblock %}
    </div>

    <div class="push"></div>
</div>

<div class="footer">
    <div class="inner-footer">
        <div class="flickr-image-slider"></div>
        <div class="flickr-image-description-container"></div>
        <div class="clear"></div>
    </div>
</div>

</body>
</html>